# Generated by Django 4.2.14 on 2026-08-18 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engagement_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.CharField(max_length=150)),
                ('auditee', models.CharField(max_length=255)),
                ('audit_year', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='moderate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_engagements', to=settings.AUTH_USER_MODEL)),
                ('lead_auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Engagement',
                'verbose_name_plural': 'Audit Engagements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['audit_year'], name='engagement_year_idx'), models.Index(fields=['department'], name='engagement_department_idx'), models.Index(fields=['status'], name='engagement_status_idx'), models.Index(fields=['risk_level'], name='engagement_risk_idx')],
            },
        ),
    ]
