# Generated by Django 4.2.14 on 2026-08-18 15:17

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_area', models.CharField(help_text='Financial statement account, business area, or audit area being assessed.', max_length=150)),
                ('assertion', models.CharField(blank=True, help_text='Relevant audit assertion, such as existence, completeness, accuracy, or valuation.', max_length=100, null=True)),
                ('risk_description', models.TextField(help_text='Description of the identified risk.')),
                ('risk_factors', models.TextField(blank=True, help_text='Factors contributing to the identified risk.', null=True)),
                ('inherent_risk_score', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Inherent risk score from 0 to 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('inherent_risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('control_risk_score', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Control risk score from 0 to 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('control_risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('romm_score', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Risk of Material Misstatement calculated from inherent and control risk.', max_digits=7)),
                ('romm_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('fraud_risk', models.BooleanField(default=False, help_text='Indicates whether fraud risk factors have been identified.')),
                ('fraud_risk_score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('anomaly_detected', models.BooleanField(default=False, help_text='Indicates whether financial-data analysis identified an anomaly.')),
                ('anomaly_score', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('auditor_assessment', models.TextField(blank=True, help_text='Professional assessment and explanation by the auditor.', null=True)),
                ('recommended_response', models.TextField(blank=True, help_text='Suggested audit response to the identified risk.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('assessed', 'Assessed'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='engagements.engagement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_risk_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Assessment',
                'verbose_name_plural': 'Risk Assessments',
                'ordering': ['-romm_score', '-created_at'],
                'indexes': [models.Index(fields=['engagement'], name='risk_engagement_idx'), models.Index(fields=['risk_area'], name='risk_area_idx'), models.Index(fields=['romm_level'], name='risk_romm_level_idx'), models.Index(fields=['status'], name='risk_status_idx'), models.Index(fields=['fraud_risk'], name='risk_fraud_idx')],
            },
        ),
    ]
