# Generated by Django 4.2.14 on 2026-08-18 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=100)),
                ('transaction_date', models.DateField(db_index=True)),
                ('department', models.CharField(db_index=True, max_length=150)),
                ('expense_category', models.CharField(db_index=True, max_length=150)),
                ('vendor_supplier', models.CharField(db_index=True, max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('budget_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('electronic', 'Electronic Payment'), ('other', 'Other')], default='bank_transfer', max_length=30)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('transaction_description', models.TextField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='engagements.engagement')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_financial_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Data',
                'verbose_name_plural': 'Financial Data',
                'ordering': ['-transaction_date', '-imported_at'],
                'indexes': [models.Index(fields=['engagement', 'transaction_date'], name='financial_eng_date_idx'), models.Index(fields=['department'], name='financial_department_idx'), models.Index(fields=['expense_category'], name='financial_category_idx'), models.Index(fields=['vendor_supplier'], name='financial_vendor_idx'), models.Index(fields=['approval_status'], name='financial_approval_idx'), models.Index(fields=['payment_status'], name='financial_payment_idx')],
            },
        ),
    ]
