# Generated by Django 4.2.14 on 2026-08-18 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('financial_statement', 'Financial Statement'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('bank_statement', 'Bank Statement'), ('budget', 'Budget'), ('contract', 'Contract'), ('audit_report', 'Audit Report'), ('policy', 'Policy'), ('supporting_document', 'Supporting Document'), ('other', 'Other')], default='other', max_length=40)),
                ('file', models.FileField(upload_to='audit_documents/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='File size in bytes.', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='engagements.engagement')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['engagement'], name='documents_d_engagem_00231c_idx'), models.Index(fields=['uploaded_by'], name='documents_d_uploade_6455fb_idx'), models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'), models.Index(fields=['processing_status'], name='documents_d_process_052924_idx'), models.Index(fields=['uploaded_at'], name='documents_d_uploade_65506e_idx')],
            },
        ),
    ]
