# Generated by Django 4.2.14 on 2026-08-18 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('objectives', models.TextField(blank=True, help_text='Objectives established for the audit.', null=True)),
                ('scope', models.TextField(blank=True, help_text='Scope and boundaries of the audit.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('approved', 'Approved'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_plans', to='engagements.engagement')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_audit_plans', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_audit_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Plan',
                'verbose_name_plural': 'Audit Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(max_length=100)),
                ('recommendation', models.TextField()),
                ('rationale', models.TextField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score from 0.00 to 100.00.', max_digits=5, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='generated', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('audit_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='planning.auditplan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_ai_recommendations', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recommendations', to='risk.risk')),
            ],
            options={
                'verbose_name': 'AI Recommendation',
                'verbose_name_plural': 'AI Recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('procedure_type', models.CharField(choices=[('inspection', 'Inspection'), ('observation', 'Observation'), ('inquiry', 'Inquiry'), ('confirmation', 'Confirmation'), ('recalculation', 'Recalculation'), ('reperformance', 'Reperformance'), ('analytical', 'Analytical Procedure'), ('other', 'Other')], default='other', max_length=30)),
                ('objective', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred')], default='planned', max_length=20)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priority of the procedure within the audit plan.')),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_audit_procedures', to=settings.AUTH_USER_MODEL)),
                ('audit_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='planning.auditplan')),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_procedures', to='risk.risk')),
            ],
            options={
                'verbose_name': 'Audit Procedure',
                'verbose_name_plural': 'Audit Procedures',
                'ordering': ['priority', 'created_at'],
                'indexes': [models.Index(fields=['audit_plan'], name='planning_au_audit_p_af2021_idx'), models.Index(fields=['risk'], name='planning_au_risk_id_cf4066_idx'), models.Index(fields=['status'], name='planning_au_status_dd8811_idx'), models.Index(fields=['assigned_to'], name='planning_au_assigne_71fd2b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='auditplan',
            index=models.Index(fields=['engagement'], name='planning_au_engagem_336582_idx'),
        ),
        migrations.AddIndex(
            model_name='auditplan',
            index=models.Index(fields=['status'], name='planning_au_status_a85379_idx'),
        ),
        migrations.AddIndex(
            model_name='auditplan',
            index=models.Index(fields=['prepared_by'], name='planning_au_prepare_3ae22a_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['audit_plan'], name='planning_ai_audit_p_693887_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['risk'], name='planning_ai_risk_id_f5297d_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['status'], name='planning_ai_status_bb0782_idx'),
        ),
    ]
