# Generated by Django 4.2.14 on 2026-08-18 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('upload', 'Upload'), ('download', 'Download'), ('approve', 'Approve'), ('reject', 'Reject'), ('process', 'Process'), ('analyze', 'Analyze'), ('export', 'Export'), ('other', 'Other')], max_length=20)),
                ('module', models.CharField(help_text='IAPS module where the action occurred.', max_length=100)),
                ('object_type', models.CharField(blank=True, help_text='Type of object affected by the action.', max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, help_text='Identifier of the affected object.', max_length=100, null=True)),
                ('description', models.TextField(help_text='Human-readable description of the action.')),
                ('old_values', models.JSONField(blank=True, help_text='Previous values before an update.', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='New values after an update.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, help_text='Identifier used to correlate an action with a request.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='audit_trail_user_id_3c17e9_idx'), models.Index(fields=['action'], name='audit_trail_action_6d962f_idx'), models.Index(fields=['module'], name='audit_trail_module_4e6fd5_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_trail_object__3384cd_idx'), models.Index(fields=['created_at'], name='audit_trail_created_cccccc_idx')],
            },
        ),
    ]
